### ISSUE TITLE
Train muti-frame model by using self-data

### ISSUE THREAD

**Issue by CodingMice** [clks-wzz/FAS-SGTD#1]
Great jobs! I want to train muti frames model  by using  myself video data. And I wonder what to know how you get frames from video? how many frames per second?

**Comment by clks-wzz** [comment]
> Great jobs! I want to train muti frames model by using myself video data. And I wonder what to know how you get frames from video? how many frames per second?

The frames per second depend on the setting of capture camera. Generally speaking, the fps of videos ranges from 25 to 30.

**Comment by CodingMice** [comment]
I mean how many frames of training data which you get from raw videos?

**Comment by clks-wzz** [comment]
https://github.com/clks-wzz/FAS-SGTD/blob/master/fas_sgtd_single_frame/generate_data_train.py#L26
https://github.com/clks-wzz/FAS-SGTD/blob/master/fas_sgtd_single_frame/generate_data_train.py#L138
You can follow these settings. We usually use 16 frames in living videos and 4 frames in spoofing videos (especially in OULU).

**Comment by CodingMice** [comment]
Thank you very much.
