### ISSUE TITLE
Encountered a problem while trying to train on multiple gpus.

### ISSUE THREAD

**Issue by 10LGUO** [clks-wzz/FAS-SGTD#13]
When I was trying to train the model on 1 or 2 gpus the code works well. But training on more than 2 gpus will cause error. Is that because of your design?  Thank you so much.

**Comment by clks-wzz** [comment]
Please show your settings of scripts and GPUs.

**Comment by 10LGUO** [comment]
still a tf version issue. Should only use tensorflow 1.14 or tensorflow-gpu 1.14 if you want to train on GPU.
