### ISSUE TITLE
Inconsistency with paper w.r.t spatial gradient & 1x1 convolution

### ISSUE THREAD

**Issue by SNeugber** [clks-wzz/FAS-SGTD#2]
Hi,

In your paper (https://arxiv.org/abs/2003.08061) you mention in formula (2) that your spatial gradient (sobel) filters are applied to the output of the 1x1 convolution in the skip connection. However in your implementation you apply the 1x1 *after* applying the sobel filters to the res block input: 

https://github.com/clks-wzz/FAS-SGTD/blob/9b813b62dcfe4467fd840f39776d3e66f5dd58e1/fas_sgtd_single_frame/util/util_network.py#L68

Could you comment on which implementation is correct please?

Thanks!

**Comment by clks-wzz** [comment]
We recommend that you can use gradient_type="type0" or "type1" in residual_gradient_conv() for stabler training.

**Comment by SNeugber** [comment]
Great, thanks!
