### ISSUE TITLE
Conv2_cd block with 3x3 instead of 1x1 convolution

### ISSUE THREAD

**Issue by SNeugber** [clks-wzz/FAS-SGTD#3]
Hi,

Given how I understand the paper that introduces the central difference convolution (https://arxiv.org/pdf/2003.04092.pdf) and its reference implementation (https://github.com/ZitongYu/CDCN/blob/master/CVPR2020_paper_codes/models/CDCNs.py#L58) we sum up the kernel of the original 3x3 convolution and use this sum to multiply it to the input via a 1x1 convolution (which is then subtracted from the output of the original 3x3 convolution).

However, your implementation here (https://github.com/clks-wzz/FAS-SGTD/blob/master/fas_sgtd_single_frame/util/util_network.py#L118) seems to suggest that you tile the sum to a 3x3 kernel, which would mean that you multiply it with the input using a receptive field of 3x3 instead of 1x1!

Can you comment on whether my understanding is correct and if so, what the reasoning behind this change is compared to the original approach?

**Comment by clks-wzz** [comment]
Thanks for your reminding. The CDCN is under verification in this project. We have fixed the difference.

**Comment by SNeugber** [comment]
Thanks for letting me know!
