### ISSUE TITLE
download model

### ISSUE THREAD

**Issue by Medencova** [clks-wzz/FAS-SGTD#6]
Hello!
Unfortunately, I can’t download your model from a baidu. Could you put your model to dropbox?
thank you very much!

**Comment by clks-wzz** [comment]
Sorry to be late to see this comment. 
Can you visit the google drive? We put the models on https://drive.google.com/drive/folders/1CW1sXkLZRUmoDjg8LpQJ8-93Baz2TB2B?usp=sharing
