### ISSUE TITLE
数据准备

### ISSUE THREAD

**Issue by huazaikai** [clks-wzz/FAS-SGTD#8]
您好，OULU这个数据集难以获得，请问如何使用自己的数据集跑通程序？

**Comment by clks-wzz** [comment]
You can follow the preprocessing script and adapt it to your own dataset: https://github.com/clks-wzz/FAS-SGTD/blob/master/fas_sgtd_single_frame/generate_data_train.py

**Comment by Roger8** [comment]
hello @clks-wzz, great work u have did. Some questions want to ask:  there r some split("_") operates in **generate_data_train.py**,i try to put my own images  data in one folder , but it failed loading; it seems like  needing specific names to run . Could u please __give an  example of the folder structure and file name example__ ?  Looking forward to your reply.
